### ISSUE TITLE
some possible clarifications for n00bs

### ISSUE THREAD

**Issue by gnmearacaun** [NapoleonWils0n/cerberus#10]
I added a couple of steps:
** solarized colour

for this and other colorschemes go to [[https://st.suckless.org/patches/]]
I extracted this code out of [[https://st.suckless.org/patches/solarized/st-solarized-dark-20180411-041912a.diff]]

replace the lines in config.def.h

#+BEGIN_SRC conf
/* Terminal colors (16 first used in escape sequence) */
................................................
in the documentation "add" implied to me that it should be added at the end of x.c rather than changing it as you say in the video:
edit x.c and change

#+begin_src sh
int
xstartdraw(void)
{
	return IS_SET(MODE_VISIBLE);
}
#+end_src

to

#+begin_src sh
int
xstartdraw(void)
{
	if (IS_SET(MODE_VISIBLE))
		XCopyArea(xw.dpy, xw.win, xw.buf, dc.gc, 0, 0, win.w, win.h, 0, 0);
	return IS_SET(MODE_VISIBLE);
}
#+end_src

.........................................
I assume from your notes that st.desktop  is created and left to remain in the source code directory to be later diffed rather than simply created and moved to .local/share/applications/

** Desktop entry

create the desktop entry file `st.desktop` 

#+begin_src sh
[Desktop Entry]
Type=Application
Name=st
Comment=simple-terminal emulator for X
Icon=utilities-terminal
Exec=st
Categories=System;TerminalEmulator
#+end_src

and copy it to ~/.local/share/applications

#+begin_src sh
cp st.desktop ~/.local/share/applications
#+end_src
........................................

the diff file isn't created until the changes are committed. so:

** create diff patch

commit the changes to the patch branch
#+begin_src sh
git add *
#+end_src

#+begin_src sh
git commit -m "customized colors and added w3m non-flicker patch"
#+end_src

**Comment by gnmearacaun** [comment]
just to be clear, I assume you mean, clone it afresh outside of the already cloned `st/`. May seem obvious, but for someone doing it the first time, confusion grows with ambiguity; there's an increased chance of errors. One starts to wonder where one went wrong. 

** apply diff patch

to apply the diff to the freshly checked out git repository

checkout the git repository outside of the working directory

#+BEGIN_SRC sh
git clone git://git.suckless.org/st
#+END_SRC

**Comment by gnmearacaun** [comment]
Towards the end of the readme the text in *st git update* is duplicated in the previous section. The following text appears twice:
If you some conflicts occur, resolve them and then record the changes and commit the result. git mergetool can help with resolving the conflicts.
Updating customizations after new release

When the time comes to update your customizations after a new release of dwm or when the dwm repository contains a commit fixing some bug, you first pull the new upstream changes into the master branch

#+BEGIN_SRC sh
git checkout master
git pull
#+END_SRC

Then rebase your customization branch on top of the master branch

#+BEGIN_SRC sh
git checkout patch
git rebase --preserve-merges master
#+END_SRC

The --preserve-merges option ensures that you don't have to resolve conflicts which you have already resolved while performing merges again.

In case there are merge conflicts anyway, resolve them (possibly with the help of git mergetool), then record them as resolved and let the rebase continue

#+BEGIN_SRC sh
git add resolved_file.ext
git rebase --continue
#+END_SRC

If you want to give up, you can always abort the rebase

#+BEGIN_SRC sh
git rebase --abort
#+END_SRC

**Comment by gnmearacaun** [comment]
text in `Merge changes into master branch` is also duplicated before heading

**Comment by NapoleonWils0n** [comment]
hi mate

sorry i missed the issues you raised
the notifications didnt come through

sometimes my notes can be a bit messy
probably due to the fact there usually done late at night

hope you managed to blunder your way through them

**Comment by gnmearacaun** [comment]
hi mate
no worries
it was a learning process and I'm happy with the results of building st.
