### ISSUE TITLE
Contribute Parts of `xmonad-ubuntu-stack-install.org` back to XMonad?

### ISSUE THREAD

**Issue by slotThe** [NapoleonWils0n/cerberus#12]
Hi,

while assisting someone getting xmonad to build correctly, they linked me [this video](https://www.youtube.com/watch?v=XvKAiR403O0) of yours about building from stack.  Full disclaimer: I didn't watch the whole thing.  However, I noticed that you mentioned that some login managers do not read `.bashrc` and similar files (as they have no reason to) and are thus not able to reliably find xmonad if it was installed with stack or cabal, as these directories are not in `$PATH` by default.

In [create a symbolic to /usr/bin/xmonad](https://github.com/NapoleonWils0n/cerberus/blob/master/xmonad/xmonad-ubuntu-stack-install.org#create-a-symbolic-to-usrbinxmonad) you mentioned that this can be fixed by simply symlinking the file to a place that the login manager will definitely find.  Would you perhaps be interested in updating INSTALL.md, more specifically, the [Make XMonad your window manager](https://github.com/xmonad/xmonad/blob/master/INSTALL.md#make-xmonad-your-window-manager) section with this information?  I would imagine it could save a lot of users some headaches

**Comment by NapoleonWils0n** [comment]
HI Mate, just saw your comment
i have created an issue on the xmonad page about creating a symbolic link to work with login managers
https://github.com/xmonad/xmonad/issues/354
