### ISSUE TITLE
Simple client PVR

### ISSUE THREAD

**Issue by hejazb** [NapoleonWils0n/cerberus#9]
Dear: Napoléon
I am trying to record an Interview from CNN (James Woolsey and Zakaria 13/11/2016). The only way I am able to see 9 seconds pieces of this video is with Simple Client PVR. I get 91 unknown channels, when I click on each channel I get about 9 seconds video, when I push Y key and select record, the CMD shell windows opens momentarily and closes then I get the OK button to finish recording pop up. But nothing gets recorded. I thought if I record 91 segments then I can use Premiere Pro to put them together.
Here is the URL. “http://cnnios-f.akamaihd.net/i/cnn/big/staging/tv/2016/11/13/exp-gps-1113-trump-foreign-policy-panel.cnn_941428_ios_,150,440,650,840,1240,.mp4.csmil/segment1_3_av.ts”
Would you please, help me to do this, using Kodi 16.1 and Simple Client PVR. Thank you in advance for the help.
Best wishes
Harry

**Comment by NapoleonWils0n** [comment]
Hi Harry
You can use youtube-dl to download the video from CNN
( you should have youtube-dl installed if you have followed my set up guide )

* How to install youtube-dl on windows
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows#youtube-dl

* youtube-dl site
https://github.com/rg3/youtube-dl

* youtube-dl supported sites ( sites you can download from )
https://rg3.github.io/youtube-dl/supportedsites.html

The video is on this page:
http://edition.cnn.com/videos/tv/2016/11/13/exp-gps-1113-trump-foreign-policy-panel.cnn

* Here's the youtube-dl command to download the video 

``
youtube-dl http://edition.cnn.com/videos/tv/2016/11/13/exp-gps-1113-trump-foreign-policy-panel.cnn
``

You just run youtube-dl and then add the url for the page

* I just downloaded the video with youtube-dl

Sorry i missed you comment best to leave a comment on the kodi-playercorefactory repo

https://github.com/NapoleonWils0n/kodi-playercorefactory

I check it more often, than this page

Re: video.ts file

Video.ts files are just small chunks of a video usually about 10-30 seconds in length,
you have an m3u8 playlist which then has links to all the video.ts files that make up the video

You really need the link to the m3u8 playlist and not the video.ts chunks
So best to avoid video.ts files if possible

Also i dont think you can record from the iptv simple client,
the iptv simple client changes the start of the url from http:// to pvr://

And ffmpeg doesnt understand urls that start with pvr://

So best to put links into the playlist loader addon and then try and record the link

You can actually record the video.ts links with the rip-record script, but they are only 9 seconds in length, so best to use youtube-dl and download from CNN

Hope that helps mate

**Comment by hejazb** [comment]
Hi Dear Sir

Thank you so much for such a detailed instruction. I was busy with Persian New Year gatherings all over the world. I did not have the chance to check my technical emails. I surely appreciate your precious work. My KODI is working fine; I can record CNN using your rip-record scripts with no problem. I am currently using your Rip Record Ver 2.2 on a Windows 10 64 bit, flawlessly. Thank you again and I wish you all the BEST.

Harry

 

Gesendet: Mittwoch, 01. März 2017 um 14:06 Uhr
Von: NapoleonWils0n <notifications@github.com>
An: NapoleonWils0n/cerberus <cerberus@noreply.github.com>
Cc: hejazb <hejazb@web.de>, Author <author@noreply.github.com>
Betreff: Re: [NapoleonWils0n/cerberus] Simple client PVR (#9)


Closed #9.

**Comment by NapoleonWils0n** [comment]
hi harry

happy persian new year

glad everything is working and you can record the channels you want
if you ever need any help feel free to get in contact

all the best mate
